import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import { NavigationMenu } from "@radix-ui/react-navigation-menu";
import ReduxProvider from "./page/redux/ReduxProvider";
import AuthObserve from "./page/redux/AuthObserve";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* ✅ Fix: Wrap ThemeProvider at top-level */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <AuthObserve />
            <NavigationMenu>
              <Navbar />
            </NavigationMenu>

            <main className="flex-1">{children}</main>

            <footer>
              <Footer />
            </footer>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
